### PR TITLE
Feature/cleanup and useability

### PR DESCRIPTION
**Pull request by jakeswenson**

### CODE REVIEW

**Comment by devshorts** [comment]
Looks tight, love the factory encapsualtion and tying both providers into one subresource container.  Can you update the readme to show how to use the new features? I realize we have no tests, so we can't leverage those as examples.  Also agree, it is a bitch to test ..., but we can probably create a super teeny dropwizard app to go alongside to help out

**Comment by jakeswenson** [comment]
I'll update the readme and add it to this pr sometime this week. Also i'll add a task to add a sample into this, similar to how drop wizard provides an example

**Comment by devshorts** [comment]
Sounds good, thanks duders

**Comment by jakeswenson** [comment]
@devshorts changed a bunch of stuff, getting ready for the dropwizard-assets library, updated the readme. Even if we use this we shouldn't release 2.0 yet. lets let it bake

**Comment by devshorts** [comment]
approved, merge it up :bug:

**Pull request merged**
